# Generated by Django 3.0.4 on 2020-03-21 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('chart_assets', models.DecimalField(decimal_places=10, max_digits=19)),
                ('chart_liabilities', models.DecimalField(decimal_places=10, max_digits=19)),
                ('chart_networth', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
